#!/usr/bin/env python3
"""
export_testset.py -- Embed a small test set + host predictions into the firmware so the device can
self-check that on-device INT8 inference matches the host (deployment correctness).

Writes firmware/main/testset.{h,c}:
  g_test_x[N_TEST][SIG_LEN]  -- normalized input signals (same space the model expects)
  g_test_y[N_TEST]           -- true labels
  g_test_pred_fp[N_TEST]     -- host FP32 argmax predictions (reference)

The device compares its INT8 argmax to g_test_pred_fp (agreement) and g_test_y (accuracy).

  conda activate qsentry
  KMP_DUPLICATE_LIB_OK=TRUE OMP_NUM_THREADS=1 python export_testset.py --run ../results/phase0 -k 64
"""
import os, sys, argparse
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE"); os.environ.setdefault("OMP_NUM_THREADS", "1")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import numpy as np
import torch
from tinybd.model import from_ckpt


def get_args():
    p = argparse.ArgumentParser()
    p.add_argument("--run", default="../results/phase0")
    p.add_argument("-k", "--num", type=int, default=64)
    p.add_argument("--outdir", default="../firmware/main")
    return p.parse_args()


def main():
    a = get_args(); dev = "cpu"
    ckpt = torch.load(os.path.join(a.run, "model.pt"), map_location=dev, weights_only=False)
    sig_len = ckpt["sig_len"]
    model = from_ckpt(ckpt)

    b = np.load(os.path.join(a.run, "bundle.npz"), allow_pickle=True)
    Xte = b["Xte"].astype(np.float32); yte = b["yte"].astype(np.int64)
    k = min(a.num, len(yte))
    X = Xte[:k]; y = yte[:k]
    with torch.no_grad():
        pred_fp = model(torch.from_numpy(X).float().unsqueeze(1)).argmax(1).cpu().numpy()
    acc = float((pred_fp == y).mean())
    print(f"[export_testset] k={k}  host FP32 acc={acc:.4f}")

    h = os.path.join(a.outdir, "testset.h"); c = os.path.join(a.outdir, "testset.c")
    with open(h, "w") as f:
        f.write(f"/* AUTO-GENERATED by export_testset.py */\n#pragma once\n"
                f"#define N_TEST {k}\n#define SIG_LEN {sig_len}\n"
                f'#ifdef __cplusplus\nextern "C" {{\n#endif\n'
                f"extern const float g_test_x[N_TEST][SIG_LEN];\n"
                f"extern const int g_test_y[N_TEST];\n"
                f"extern const int g_test_pred_fp[N_TEST];\n"
                f"#ifdef __cplusplus\n}}\n#endif\n")
    with open(c, "w") as f:
        f.write('/* AUTO-GENERATED by export_testset.py */\n#include "testset.h"\n\n')
        f.write("const float g_test_x[N_TEST][SIG_LEN] = {\n")
        for i in range(k):
            row = ",".join(f"{v:.6e}f" for v in X[i])
            f.write("  {" + row + "},\n")
        f.write("};\n\n")
        f.write("const int g_test_y[N_TEST] = {" + ",".join(str(int(v)) for v in y) + "};\n")
        f.write("const int g_test_pred_fp[N_TEST] = {" + ",".join(str(int(v)) for v in pred_fp) + "};\n")
    print(f"[export_testset] wrote {os.path.abspath(h)} and {os.path.abspath(c)}")


if __name__ == "__main__":
    main()
