#!/usr/bin/env python3
"""
export_monitor.py -- Generate firmware/main/monitor_params.c from a trained C3 detector.

Dumps the class-conditional activation-monitor parameters (per predicted class: median[] and
inv_mad[] = 1/MAD at the penultimate 'gap' layer) as C arrays matching qsentry_bench.c's
externs g_median[N_CLASSES][MONITOR_DIM] / g_inv_mad[N_CLASSES][MONITOR_DIM]. This is the last
piece needed for the firmware to compile (once the esp-dl model calls are wired).

  conda activate qsentry
  KMP_DUPLICATE_LIB_OK=TRUE OMP_NUM_THREADS=1 python export_monitor.py --run ../results/phase0
"""
import os, sys, argparse
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE"); os.environ.setdefault("OMP_NUM_THREADS", "1")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import numpy as np
import torch

from tinybd import quant as Q, defense as Def
from tinybd.model import VibCNN


def get_args():
    p = argparse.ArgumentParser()
    p.add_argument("--run", default="../results/phase0")
    p.add_argument("--layer", default="gap")
    p.add_argument("--clipK", type=float, default=8.0)
    p.add_argument("--out", default="../firmware/main/monitor_params.c")
    return p.parse_args()


def fmt_array_2d(name, A):
    C, D = A.shape
    rows = ",\n".join("  { " + ", ".join(f"{v:.8e}f" for v in A[c]) + " }" for c in range(C))
    return f"const float {name}[{C}][{D}] = {{\n{rows}\n}};\n"


def main():
    a = get_args(); dev = "cpu"
    ckpt = torch.load(os.path.join(a.run, "model.pt"), map_location=dev, weights_only=False)
    bits = ckpt["bits"]; nclass = ckpt["n_classes"]
    model = VibCNN(n_classes=nclass, seed=0, width=ckpt.get("width", 1)).to(dev)
    model.load_state_dict(ckpt["state_dict"]); model.eval()

    b = np.load(os.path.join(a.run, "bundle.npz"), allow_pickle=True)
    Xcal = torch.from_numpy(b["calib"]).float().unsqueeze(1).to(dev)
    wq, _, _ = Q.make_wq(model.p, bits)
    scales = Q.calibrate_act_scales(wq, Xcal, bits)

    _, cstats = Def.calibrate(model, wq, scales, bits, Xcal, a.layer, nclass, a.clipK)
    D = model.gap_dim
    median = np.zeros((nclass, D), np.float64)
    inv_mad = np.zeros((nclass, D), np.float64)
    for c in range(nclass):
        m, mad = cstats[c]
        median[c] = m
        inv_mad[c] = 1.0 / mad

    header = (f"/* AUTO-GENERATED by export_monitor.py from {os.path.abspath(a.run)}\n"
              f" * C3 class-conditional activation monitor params (layer='{a.layer}', INT{bits}).\n"
              f" * N_CLASSES={nclass}, MONITOR_DIM={D}, TIER1_CLIP_K={a.clipK}.\n"
              f" * Ensure qsentry_bench.c #defines match these (N_CLASSES, MONITOR_DIM).\n */\n\n")
    body = fmt_array_2d("g_median", median) + "\n" + fmt_array_2d("g_inv_mad", inv_mad)

    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    with open(a.out, "w") as f:
        f.write(header + body)
    print(f"[export_monitor] wrote {os.path.abspath(a.out)}  (N_CLASSES={nclass}, MONITOR_DIM={D})")
    if D != 64 or nclass != 4:
        print(f"[export_monitor] NOTE: update qsentry_bench.c -> #define MONITOR_DIM {D}, N_CLASSES {nclass}")


if __name__ == "__main__":
    main()
